site_name: Obsidian Vault
site_url: https://costbinne.github.io/obsidianVault/

theme:
  name: material

docs_dir: forithen_Vault/public
site_dir: site

nav:
  - Home: index.md

plugins:
  - search
  - roamlinks